#!/usr/bin/env bash
set -ex

cd fuzzy_linear_programming
# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
jupyter nbconvert \
	--to 'html' \
	--ExecutePreprocessor.allow_errors=True \
	--ExecutePreprocessor.timeout=-1 \
	--FilesWriter.build_directory=../results \
	--execute pulp_linprog.ipynb
