# hash:sha256:3feebb2638ed1e3fb082428d167d052d9e2903beb84ab879353328c3a98d4259
FROM registry.codeocean.com/codeocean/miniconda3:4.12.0-python3.9-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive


RUN pip3 install -U --no-cache-dir \
    jupyterlab==3.6.3 \
    matplotlib==3.7.1 \
    numpy==1.23.5 \
    pandas==2.0.1 \
    pulp==2.7.0 \
    scikit-fuzzy==0.4.2 